### Exploratory Data Analysis

I saw that some publication years were year 0

In [1]:
import pandas as pd

book_data = pd.read_csv('../../data/Books.csv', low_memory=False)
user_data = pd.read_csv('../../data/Users.csv', low_memory=False)
rating_data = pd.read_csv('../../data/Ratings.csv', low_memory=False)

book_data.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [2]:
print(book_data.shape)
print(user_data.shape)
print(rating_data.shape)

(271360, 8)
(278858, 3)
(1149780, 3)

In [3]:
#book_data_path.iloc[0]

In [4]:
#book_data_path.loc[0]

In [5]:
numeric_years = pd.to_numeric(book_data['Year-Of-Publication'], errors='coerce')
filtered_df = book_data[(numeric_years < 10) | (numeric_years.isna())]
print(filtered_df.shape)
filtered_df.head()

(4621, 8)

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
176,3150000335,Kabale Und Liebe,Schiller,0,"Philipp Reclam, Jun Verlag GmbH",http://images.amazon.com/images/P/3150000335.0...,http://images.amazon.com/images/P/3150000335.0...,http://images.amazon.com/images/P/3150000335.0...
188,342311360X,Die Liebe in Den Zelten,Gabriel Garcia Marquez,0,Deutscher Taschenbuch Verlag (DTV),http://images.amazon.com/images/P/342311360X.0...,http://images.amazon.com/images/P/342311360X.0...,http://images.amazon.com/images/P/342311360X.0...
288,0571197639,Poisonwood Bible Edition Uk,Barbara Kingsolver,0,Faber Faber Inc,http://images.amazon.com/images/P/0571197639.0...,http://images.amazon.com/images/P/0571197639.0...,http://images.amazon.com/images/P/0571197639.0...
351,3596214629,"Herr Der Fliegen (Fiction, Poetry and Drama)",Golding,0,Fischer Taschenbuch Verlag GmbH,http://images.amazon.com/images/P/3596214629.0...,http://images.amazon.com/images/P/3596214629.0...,http://images.amazon.com/images/P/3596214629.0...
542,8845229041,Biblioteca Universale Rizzoli: Sulla Sponda De...,P Coelho,0,Fabbri - RCS Libri,http://images.amazon.com/images/P/8845229041.0...,http://images.amazon.com/images/P/8845229041.0...,http://images.amazon.com/images/P/8845229041.0...

In [6]:
numeric_years = pd.to_numeric(book_data['Year-Of-Publication'], errors='coerce')

new_book_data = book_data[(numeric_years >= 500) & (numeric_years.notna())]
new_book_data.shape

(266739, 8)

In [20]:
# check null values for string columns
target_columns = ['ISBN', 'Book-Title', 'Book-Author']

print("True Null Counts:")
print(book_data[target_columns].isna().sum())

True Null Counts:
ISBN           0
Book-Title     0
Book-Author    0
dtype: int64

In [15]:
broken_rows_mask = book_data['Book-Author'].isna() | book_data['Publisher'].isna()

print(book_data[broken_rows_mask][['ISBN', 'Book-Title', 'Book-Author']])

              ISBN                                         Book-Title  \
118033  0751352497                           A+ Quiz Masters:01 Earth
128890  193169656X                                        Tyrant Moon
129037  1931696993                                    Finders Keepers
187689  9627982032  The Credit Suisse Guide to Managing Your Perso...

            Book-Author                       Publisher
118033              NaN              Dorling Kindersley
128890  Elaine Corvidae                             NaN
129037  Linnea Sinclair                             NaN
187689              NaN  Edinburgh Financial Publishing

In [13]:
for col in target_columns:
    empty_count = (book_data[col].astype(str).str.strip() == "").sum()
    print(f"{col}: {empty_count} blank rows")

ISBN: 0 blank rows
Book-Title: 0 blank rows
Book-Author: 0 blank rows
Publisher: 0 blank rows

In [21]:
# full clean
book_data = pd.read_csv('../../data/Books.csv', low_memory=False)
book_data = book_data.drop(columns=['Image-URL-S', 'Image-URL-M', 'Image-URL-L', "Publisher"])
book_data = book_data.dropna(subset=['Book-Author'])
book_data['Year-Of-Publication'] = pd.to_numeric(book_data['Year-Of-Publication'], errors='coerce')
initial_count = len(book_data)
book_data = book_data[book_data['Year-Of-Publication'].notna() & (book_data['Year-Of-Publication'] > 0)]
book_data['Year-Of-Publication'] = book_data['Year-Of-Publication'].astype(int)
print(book_data.shape)
book_data.head()
book_data.to_csv("../data/Books_clean.csv", index=False)

(266737, 4)